#ifndef EEPROM_ADDRESSES_H
#define EEPROM_ADDRESSES_H

#define EEPROM_LAST_MODE 0

#define EEPROM_MOON_START_HR 1
#define EEPROM_MOON_START_MIN 2
#define EEPROM_SUN_START_HR 3
#define EEPROM_SUN_START_MIN 4

#endif